remove user since pip will not be installed as root
gengo/geoip-lite-api pull request #7
Opened 2023-02-09 09:33 UTC by markjezreeldagot

As a result of having User on the python.
The python will no longer be installed as Root.
You then need to specify the /home/python/bin/aws to execute awscli rather than directly calling aws command

2023-02-09 09:47 UTC, mervinsanandres approved these changes

2023-02-09 09:55 UTC, MedelDomingo approved these changes

2023-02-09 10:03 UTC, ninotoshi reviewed
actually it's better to just add this line before `ENTRYPOINT`
```
RUN echo 'PATH=/home/python/.local/bin:$PATH' >> .bashrc
```

2023-02-10 01:38 UTC, ninotoshi requested changes
I mean
- revert both 7380e3e47bae28d685b501c0820635baf947e65c and 96fd1336362d4122542512f63cd284f6b57faf88
- put this before `ENTRYPOINT`
  `RUN echo 'PATH=/home/python/.local/bin:$PATH' >> .bashrc`

Probably it's better to open a new PR.

2023-02-10 01:39 UTC, markjezreeldagot commented
okay @ninotoshi  thanks

2023-02-10 01:39 UTC, closed without merging